### ISSUE TITLE
Large Attachments

### ISSUE THREAD

**Issue by mmmries** [couchrest/couchrest#107]
It looks like currently [Document#put_attachment](https://github.com/couchrest/couchrest/blob/de04ebc550649707c869c23f325696cb347655a8/lib/couchrest/helper/attachments.rb#L5) reads the entire file into memory during the PUT request. The details of where this happen look like they are upstream in the rest_client gem. I am posting the issue here, because I think there are a lot of other people who specifically want to use CouchDB in order to attach large files to their documents.

Is there a way to attach large files using a streaming request? Maybe I just missed it in my dive through the documentation? Does this need to be addressed upstream?

**Comment by samlown** [comment]
Although I've not tested large files specifically, the new 2.0.0 (beta2) release should support streaming upload of File IO objects thanks to the HTTPClient library. Did you want to give it a try and let me know how it goes?

**Comment by samlown** [comment]
No news is good news, so I'm assuming this is okay. Please re-open if not the case!
