### ISSUE TITLE
A database containing slashes make it crash

### ISSUE THREAD

**Issue by maoueh** [couchrest/couchrest#120]
Testing with `gem 'couchrest', '~> 2.0.0.rc3'`.

```
require 'couchrest'

CouchRest.new('http://localhost:5984').database!('prod/result')
```

Results in the following exception:

```
C:/Local/Ruby/2.1.7/lib/ruby/gems/2.1.0/gems/couchrest-2.0.0.rc3/lib/couchrest/connection.rb:225:in `raise_response_error': 404 Not Found (CouchRest::NotFound)
        from C:/Local/Ruby/2.1.7/lib/ruby/gems/2.1.0/gems/couchrest-2.0.0.rc3/lib/couchrest/connection.rb:180:in `handle_response_code'
        from C:/Local/Ruby/2.1.7/lib/ruby/gems/2.1.0/gems/couchrest-2.0.0.rc3/lib/couchrest/connection.rb:169:in `send_and_parse_response'
        from C:/Local/Ruby/2.1.7/lib/ruby/gems/2.1.0/gems/couchrest-2.0.0.rc3/lib/couchrest/connection.rb:154:in `execute'
        from C:/Local/Ruby/2.1.7/lib/ruby/gems/2.1.0/gems/couchrest-2.0.0.rc3/lib/couchrest/connection.rb:72:in `put'
        from C:/Local/Ruby/2.1.7/lib/ruby/gems/2.1.0/gems/couchrest-2.0.0.rc3/lib/couchrest/server.rb:51:in `create_db'
        from C:/Local/Ruby/2.1.7/lib/ruby/gems/2.1.0/gems/couchrest-2.0.0.rc3/lib/couchrest/server.rb:41:in `rescue in database!'
        from C:/Local/Ruby/2.1.7/lib/ruby/gems/2.1.0/gems/couchrest-2.0.0.rc3/lib/couchrest/server.rb:38:in `database!'
        from db_with_slash.rb:4:in `<main>'
```

Problem is present either if the database exists or not. The problem is that the database is not escaped when doing the request to CouchDB. Using this instead make it work correctly:

```
require 'couchrest'

CouchRest.new('http://localhost:5984').database!('prod%2Fresult')
```

Regards,
Matt

**Comment by ahodgkinson** [comment]
The pattern: 

    CouchRest.new('server_url').database('db_name') 

can also be used to access a database where the CouchDB server is accessed via a relative path with respect to the hostname. This can be useful when you access the CouchDB server via a proxy assigned to a relative path. For example:

    CouchRest.new('http://example.com/couch').database('mydb')

**Comment by samlown** [comment]
This issue should be fixed with this commit: https://github.com/couchrest/couchrest/commit/4469ea5c77c7cff1d650c12629c90aa1e9cf679d, please confirm @maoueh

**Comment by maoueh** [comment]
I don't have the code anymore. I trust you that's it's fixed, thanks :+1
