### ISSUE TITLE
No substitutions of url unsafe characters in database and document names.

### ISSUE THREAD

**Issue by magic2k** [couchrest/couchrest#122]
Such checking only taking place in https://github.com/couchrest/couchrest/blob/master/lib/couchrest/database.rb#L29

`    def initialize(server, name)
      @name     = name
      @server   = server
      @path     = "/#{name.gsub('/','%2F')}"`

This should be occured when trying to get database or document by its name at least for these symbols:

```
 / = %2F
 - = %2D
```

**Comment by samlown** [comment]
@magic2k this *should* be fixed now! We added some extra code in this commit: https://github.com/couchrest/couchrest/commit/4469ea5c77c7cff1d650c12629c90aa1e9cf679d Could you please confirm?

**Comment by magic2k** [comment]
Thank you!
