### ISSUE TITLE
cannot use hash keys with save_doc

### ISSUE THREAD

**Issue by schmurfy** [couchrest/couchrest#124]
Apparently this was already fixed a while ago but broke again, if you do that:

``` ruby
db.save_doc(_id: "some_id", ...)
```

the gem only tries to read `doc["_id"]` which returns nothing, hash with symbol keys should either be allowed everywhere or nowhere.
The previous fix was to add this at the top of save_doc method:

``` ruby
doc = Document.new(doc)
```

I don't know the code enough to propose a pull request but I can give it a try.

**Comment by samlown** [comment]
@schmurfy this is kind of intended practice, the `Database#save_doc` method is considered pretty low level and assumes you'll be using hashes with string keys, as this is what it always returns, and indeed replaces. Indeed, saving a hash in this way will automatically set the `doc["_rev"]` key.

The `Document` however adds additional wrappers to avoid the confusion with symbols and strings.

I'd be interested in hearing other thoughts on this!

**Comment by schmurfy** [comment]
My issue is that the example above will work but partly and that's why I consider a bug: the request will be sent to couchdb and all your fields will be there if you run a tcpdump  but the path it will write to is wrong.

Either save_doc is considered an internal api and you should clearly state it by making it private or its behaviour should be rational, it caused me some headache trying to figure out why my _id field was ignored xD

Another problem might be that the README example use save_doc, not the Document class ;)
Honestly I did not even notice the Document interface, I am currently just using this gem for prototyping and I just went with the README example and worked from there.

**Comment by samlown** [comment]
I understand your point, but I'm really not sure what the correct solution is. I don't think this is the right part of the code to deal with key conversion as the objective is to keep couchrest as compact and lightweight as possible. Converting to a Document adds overhead, hence why it was removed.

For a start, we can try to improve the documentation.

**Comment by schmurfy** [comment]
yes I agree, documentation might just be the issue here, having a lowlevel and higher api is entirely fine as long as users are clear on what is what ^^

**Comment by naven87** [comment]
I think I'm seeing the same problem, where using save_doc with a hash with symbol keys fails directly complaining about no method [] for 0:Integer, but if I merge it with an empty Hash.new, it works fine.  I was just following the readme so I didn't know about using Document.

**Comment by schmurfy** [comment]
@naven87 You should create a new issue if you want but I am closing this one as the project seems abandonned and I have no longer any use for it.
