### ISSUE TITLE
Avoid put requests to _design docs when accessing views

### ISSUE THREAD

**Issue by jawosis** [couchrest/couchrest#27]
CouchDB's security module allows to explicitly define who can update _design docs on a db level.
Consider a db which grants public access to its views but just allows admin users to modify or create _design docs --> current couchrest wouldn't be able to show the pubic views as by default every db request triggers a put request to the _design docs and thus would end in an error.

**Comment by samlown** [comment]
This issue no longer happens in CouchRest Model. Closing.
