### ISSUE TITLE
SystemStackError: stack level too deep 

### ISSUE THREAD

**Issue by mattandgeorge** [couchrest/couchrest#29]
With:

json gem 1.4.3
couchrest 0.37
rails 3 beta 2
Ruby 1.8.7 Mac OS 10.6
Couchdb 0.12.0a2c10462-git

I get the following error when the model is accessed the first time with for example Post.all

http://pastie.org/956935

If I do another Post.all then it works and I get a list of Posts.

If I downgrade the json gem to 1.2.4 this problem goes away. I've not tried other versions of this gem.

**Comment by samlown** [comment]
Probably fine now. Closing.
