### ISSUE TITLE
Large attachments fail with timeout error

### ISSUE THREAD

**Issue by heisters** [couchrest/couchrest#33]
When I try to attach a 50MB file on a slow server (small EC2 instance), I get this error:

<pre>
RestClient::RequestTimeout: Request Timeout
from /home/deploy/.bundle/ruby/1.8/gems/rest-client-1.5.1/lib/restclient/request.rb:147:in `transmit'
from /home/deploy/.bundle/ruby/1.8/gems/rest-client-1.5.1/lib/restclient/request.rb:56:in `execute'
from /home/deploy/.bundle/ruby/1.8/gems/rest-client-1.5.1/lib/restclient/request.rb:31:in `execute'
from /home/deploy/.bundle/ruby/1.8/gems/rest-client-1.5.1/lib/restclient.rb:76:in `put'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/core/adapters/restclient.rb:21:in `put'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/core/rest_api.rb:6:in `put'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/core/database.rb:176:in `save_doc'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/more/extended_document.rb:244:in `save_without_callbacks'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/more/extended_document.rb:218:in `update'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/mixins/callbacks.rb:413:in `_run_save_callbacks'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/more/extended_document.rb:217:in `update'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/mixins/callbacks.rb:403:in `_run_update_callbacks'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/more/extended_document.rb:216:in `update'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/more/extended_document.rb:212:in `catch'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/more/extended_document.rb:212:in `update'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/more/extended_document.rb:234:in `save'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/more/extended_document.rb:228:in `catch'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/more/extended_document.rb:228:in `save'
from /home/deploy/.bundle/ruby/1.8/gems/couchrest-0.37/lib/couchrest/more/extended_document.rb:252:in `save!'
</pre>

This monkeypatch fixes the problem (albeit inelegantly):

<pre>
module RestClient
  def self.put(url, payload, headers={}, &block)
    RestClient::Request.execute(
      :method => :put,
      :url => url,
      :payload => payload,
      :headers => headers,
      :timeout => 300, &block)
  end
end
</pre>

First question: why does it take so long? It appears the default timeout is about 60 seconds. Uploading the same attachment with curl takes about 8 seconds. The timeout starts after CouchRest does its Base64 encoding (which takes about 14 seconds), so that's not the issue.

Second question: is there a better way to extend the timeout? Ideally, this would be intelligent--ie. if the payload is bigger, allow a longer timeout, as it seems that time scales geometrically with the size of the attachment.

**Comment by samlown** [comment]
D'oh! Should no longer be an issue with the 2.0.0 as the HTTPClient supports File objects.
