### ISSUE TITLE
bug: attachments encoded multiple times

### ISSUE THREAD

**Issue by moonmaster9000** [couchrest/couchrest#37]
hi, 

in attempting to implement a versioning gem that builds on top of couchrest_model, i discovered the following problem with couchrest: saving a document with inline attachments multiple times without a reload will cause repeated base64 encodings of the attachment data (i.e., a base64 encoding of something that's already been base64 encoded). 

steps to reproduce:

open irb. create a doc with an inline attachment. save it. change a property. save it again. your attachment has now been base64 encoded twice.

**Comment by samlown** [comment]
This is still an issue. The problem boils down to the fact that the library does not do anything with the attachment data after the document is saved.

I think the solution is to `freeze` the attachment data once it's been converted to Base64. The only issue with this is that the file may end up being uploaded twice, but the advantage is that it simplifies error handling. I'll get this into CouchRest 2.0.

Regardless, I'd always recommend using the `Database#put_attachement` method.

**Comment by samlown** [comment]
Okay, this is now fixed, and will be packaged with CouchRest 2.0.

https://github.com/samlown/couchrest/blob/persistent/lib/couchrest/database.rb#L383
