### ISSUE TITLE
Bulk save of extended docs with timestamps! does not save created_at or updated_at fields

### ISSUE THREAD

**Issue by grempe** [couchrest/couchrest#4]
When a model is created that extends Couchrest::ExtendedDocument and it has the 'timestamps!' property in the model it is expected that a 'created_at' and 'updated_at' timestamp field will be created when the document is saved.  It should not matter if the document was saved singly or using the bulk save mechanism.

This only works as expected when docs are created and saved singly.  Bulk document saves do not create the expected fields.

Please find an example of this at : http://pastie.org/652473

The example first shows creating and saving an individual doc with timestamps created properly.  The second part shows creating multiple docs and bulk saving them with no timestamps created after save.

**Comment by samlown** [comment]
Closing. CouchRest Model does this stuff now.
