### ISSUE TITLE
keep-alive connections

### ISSUE THREAD

**Issue by prettynatty** [couchrest/couchrest#43]
Hello.
My rake task makes over 1000 requests(db.view('uri-here'))  to the database.
I get an error "getaddrinfo name or service not known".
When I have inspected the script using strace I found that this error raised because too much files(socket = file in unix) were open.
And when the script shutting down(I catch all exceptions) strace is showing me "close" methods of all created sockets.
I have tried to execute GC.start but this didn't make me any profit.
Is it possible to use keep-alive connections with couchrest?

**Comment by samlown** [comment]
This is now sorted in CouchRest 2.0 thanks to HTTPClient. Finally!
