### ISSUE TITLE
monkeypatch for Net::BufferedIO for 1.8 should rescue EAGAIN as well

### ISSUE THREAD

**Issue by nahi** [couchrest/couchrest#44]
couchrest/monkeypatches.rb replaces rbuf_fill but it seems not compatible with 1.9's one.

cf. http://jira.codehaus.org/browse/JRUBY-5075

IO#read_nonblock can raise any error defined in read(2) system call. And POSIX.1-2001 allows either error of EAGAIN and EWOULDBLOCK to be returned from read(2), and also allows both error value are not the same.

So, couchrest should rescue EAGAIN as well as EWROULDBLOCK for portability I think. Windows is a platform that has different error value for EAGAIN and EWOULDBLOCK so mswin32 CRuby must raise the same error for couchrest.

**Comment by samlown** [comment]
This still an issue? closing for the time being.
