### ISSUE TITLE
Ruby 1.8.6 issues warning to parenthesize arguments for abstract_response.rb

### ISSUE THREAD

**Issue by science** [couchrest/couchrest#51]
I wish I knew how to submit a patch but I'm pretty weak in git. When running a ruby file with a single line:

require("couchrest")

I get the warning:
C:/apps/ruby/lib/ruby/gems/1.8/gems/rest-client-1.6.1/lib/restclient/abstract_re
sponse.rb:50: warning: parenthesize argument(s) for future version

I find that changing line 50 of that file to this eliminates the warning (and I believe does not change the intended function):
raise RequestFailed(self)

I hope this is helpful - contact me if you need additional info.

Steve

**Comment by samlown** [comment]
1.8.6 is no longer supported. Closing.
