### ISSUE TITLE
Request timeout problem

### ISSUE THREAD

**Issue by imcsk8** [couchrest/couchrest#54]
Hello,

I'm testing couchrest on a rails application with no much success so far, i've created my application structure using the scaffold functionality without much trouble but when i try to access it i get a "Request Timeout" error i've digged the code around and i've changed the timeout manually (to 1000) on the file "/var/lib/gems/1.8/gems/rest-client-1.6.1/lib/restclient/request.rb" just for the pourpouse of testing and i get a "RestClient::ServerBrokeConnection" error.
I found that i'm getting this error when couchrest tries to insert the javascript code of a view that shows all the elements of the database. I copied the view's code and inserted it using both curl and futon without any problem or delay in response.

¿can somebody give a hint on can i solve this problem?

thanks

**Comment by samlown** [comment]
This should be fixed since a while back as CouchRest no longer attempts to do anything with views. Please re-open if not the case.
