### ISSUE TITLE
User creation

### ISSUE THREAD

**Issue by ahamid** [couchrest/couchrest#56]
Is user creation something that would be considered in scope for this library?  E.g.:

    def self.create_user_doc(username, password, roles = [])
      doc = {
        :name => username,
        :_id => "org.couchdb.user:" + username,
        :type => "user",
        :roles => (roles || [])
      }
      if !password.nil?
        doc[:salt] = UUID.generate
        doc[:password_sha] = Digest::SHA1.hexdigest(password + doc[:salt])
      end
      return doc
    end

**Comment by samlown** [comment]
4 and a half years later... I think this is a useful feature, but I'm not convinced on the User Document part. Given that this is a one-way process, i.e. fetching a user returns a regular `Document`, I think a `UserDocument` abstraction is beneficial.

If this is still useful, I'd suggest sticking `create_user` document in the `Server` class.
