### ISSUE TITLE
Check if couchdb document is available

### ISSUE THREAD

**Issue by thomaswitt** [couchrest/couchrest#66]
I wrote a small extension to check via HTTP HEAD request whether an document exists at all. Maybe CouchRest could support that out of the box?

```
module CouchRest
  class Database
    def exists?(id)
      return false if id.blank?
      slug = escape_docid(id)
      url = CouchRest.paramify_url("#{@root}/#{slug}")
      begin
        RestClient.head(url)
      rescue
        return false
      end
      return true
    end
  end
end
```

**Comment by samlown** [comment]
I'm not 100% convinced this is necessary, as `exists?` is not really a HTTP method. It would be more appropriate for example in couchrest_model. I'd suggest doing it this way:

```ruby
begin
  CouchRest.head("#{url}/#{doc_id}")
  true
rescue CouchRest::NotFound
  false
end
```
