### ISSUE TITLE
HTTP Proxy Support for replication

### ISSUE THREAD

**Issue by mujhs** [couchrest/couchrest#74]
Does the current API support replication through an http proxy? Looking through the source it does not  look that way.

From http://wiki.apache.org/couchdb/Replication

> Replicating through a proxy

> Pass a "proxy" argument in the replication data to have replication go through an HTTP proxy:

> POST /_replicate HTTP/1.1
>{"source":"example-database","target":"http://example.org/example-database", "proxy":"http://localhost:8888"}

**Comment by samlown** [comment]
This isn't supported in the CouchRest API, but my recommendation would be to create documents directly in the replicator database which will give you much more control with this type of advanced requirement:

```ruby
doc = {
  "source" => "example-database",
  "target"  => "http://example.org/example-database",
  "proxy"  => "http://localhost:8888"
}
db = CouchRest.new.database!('_replicator')
db.save_doc(doc)  # Replication should start automatically
```
