### ISSUE TITLE
Problem with map/reduce functions syntax

### ISSUE THREAD

**Issue by akrivoruchko** [couchrest/couchrest#82]
Hello!

I'm testing couchrest with couchdb 1.1.1-1 (Debian wheesy) and views not working at all. 

Cause of the problem described here: https://issues.apache.org/jira/browse/COUCHDB-1302

In a nutshell an anonymous function at the root of a scope is invalid JavaScript. I.e., the following is invalid: "function(doc) {...}" and SpiderMonkey (used by couchdb) ceased to allow this by default. Correct definition is "(function(doc){...})". 
So, I propose to upgrade map/reduce function definitions. 
I think it is pretty easy to do, but I'm not familiar with git. May be somebody can help.

Thanks!

**Comment by samlown** [comment]
Oh my! I think this should be handled at the CouchDB level as opposed to CouchRest. Adding `()` around every function could create some serious hassle. Closing this for the time being.
