### ISSUE TITLE
Database#view does not accept one-character design names

### ISSUE THREAD

**Issue by stomar** [couchrest/couchrest#84]
When trying to access a view, a design with a name consisting of only one character results in an error (404 Resource Not Found). The problem lies in the `name_to_view_path` method.

Example code:

```ruby
@db = CouchRest.database!('http://127.0.0.1:5984/couchrest_test')

@db.bulk_save([
  {"word" => "once"},
  {"word" => "and again"}
])

view = {'all' => {'map' => <<-JS
  function(doc) {
    emit(doc.word,null);
  }
JS
}}

@db.save_doc({
  "_id" => "_design/A",
  :views => view
})

r = @db.view('A/all')  # => error
puts r['total_rows'] == 2
```

Changing `_design/A` to `_design/AB` works fine.

**Comment by samlown** [comment]
Fixed for CouchRest 2.0: https://github.com/samlown/couchrest/blob/persistent/lib/couchrest/database.rb#L395
