### ISSUE TITLE
multi_json 1.5.1 breaks object decoding

### ISSUE THREAD

**Issue by m1foley** [couchrest/couchrest#92]
Commit that broke CouchRest:
https://github.com/intridea/multi_json/commit/193e28cf4dc61b6e7b7b7d80f06f74c76df65c41

Security issue:
http://seclists.org/oss-sec/2013/q1/283

CouchRest method that is now broken:
[CouchRest::RestAPI#parse_response](https://github.com/couchrest/couchrest/blob/master/lib/couchrest/rest_api.rb#L149)

Steps to recreate:
Update multi_json from 1.5.0 to 1.5.1. Instead of a Ruby object parsed from the JSON.create_id field, CouchRest#get now returns a Hash.

Workaround:
I couldn't figure out how to best fix the CouchRest code, but this monkey patch can be used as a workaround:
```ruby
module JSON
  class << self
    alias :old_parse :parse
    def parse(json, args = {})
      args[:create_additions] = true
      old_parse(json, args)
    end
  end
end
```

**Comment by samlown** [comment]
The `CouchRest.decode_json_objects` attribute supports this now. Closing.
